version: "3"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data_db:/data/db
    ports:
      - "27017:27017"
  api:
    image: node:18
    working_dir: /usr/src/api-clean-node
    restart: always
    command: bash -c "npm install --omit=dev && npm start"
    volumes: 
      - ./dist/:/usr/src/api-clean-node/dist/
      - ./package.json:/usr/src/api-clean-node/package.json
    ports:
      - "5050:5050"
    links:
      - mongo

